Repository ladybug-tools/ladybug, pull requests merged in 2019-03, with the labels that each got.

#108 Datacollection Refactor
  ladybug/_datacollectionbase.py
  ladybug/analysisperiod.py
  ladybug/datacollection.py
  ladybug/datapoint.py
  ladybug/datatype/base.py
  ladybug/datatype/generic.py
  ladybug/datatype/percentage.py
  ladybug/datatype/temperature.py
  ladybug/designday.py
  ladybug/epw.py
  ladybug/header.py
  ladybug/location.py
  ladybug/skymodel.py
  ladybug/stat.py
  ladybug/wea.py
  tests/analysisperiod_test.py
  tests/datacollection_test.py
  tests/datapoint_test.py
  tests/designday_test.py
  tests/epw_test.py
  tests/location_test.py
  tests/stat_test.py
  tests/wea_test.py
Labels: enhancement, new development

#113 feat(datatype): Add Data Types for Thermal Comfort
  ladybug/_datacollectionbase.py
  ladybug/datacollection.py
  ladybug/datatype/percentage.py
  ladybug/datatype/temperature.py
  ladybug/datatype/temperaturedelta.py
  ladybug/datatype/thermalcondition.py
  ladybug/psychrometrics.py
  tests/datacollection_test.py
  tests/datatype_test.py
Labels: enhancement

#114 fix(analysisperiod): fixed end_hour input value check
  README.md
  ladybug/analysisperiod.py
  tests/analysisperiod_test.py
Labels: bug

#116 feat(datacollection): Consolidate Code
  ladybug/_datacollectionbase.py
  ladybug/datacollection.py
  ladybug/datatype/base.py
  ladybug/datatype/energyflux.py
  ladybug/datatype/percentage.py
  ladybug/datatype/rvalue.py
  ladybug/datatype/thermalcondition.py
  tests/datacollection_test.py
Labels: enhancement

#119 fix(datatype): Putting epw missing, min, and max valules on EPW
  ladybug/_datacollectionbase.py
  ladybug/datacollection.py
  ladybug/datatype/angle.py
  ladybug/datatype/base.py
  ladybug/datatype/energyflux.py
  ladybug/datatype/energyintensity.py
  ladybug/datatype/fraction.py
  ladybug/datatype/generic.py
  ladybug/datatype/illuminance.py
  ladybug/datatype/luminance.py
  ladybug/datatype/pressure.py
  ladybug/datatype/speed.py
  ladybug/datatype/temperature.py
  ladybug/epw.py
  tests/datacollection_test.py
Labels: enhancement

#120 fix(location): Fixing Location.duplicate() method
  ladybug/location.py
  tests/location_test.py
Labels: bug

#121 feat(datacollection): Added Immutable Types for Data Collections
  ladybug/__init__.py
  ladybug/_datacollectionbase.py
  ladybug/datacollection.py
  ladybug/datacollectionimmutable.py
  tests/datacollection_test.py
  tests/datacollectionimmutable_test.py
Labels: enhancement

#122 docs(sphinx): Added automated API documentation
  .travis.yml
  docs/README.md
  docs/_build/README.md
  docs/_build/docs/README.md
  docs/conf.py
  docs/index.rst
  docs/modules.rst
Labels: documentation, enhancement
