Repository ladybug-tools/ladybug, pull requests merged in 2019-08, with the labels that each got.

#154 feat(datatype): Adding data types for schedule type limits
  ladybug/datatype/power.py
  ladybug/datatype/uvalue.py
Labels: enhancement

#156 feat(date, time): Add objects for Date and Time
  ladybug/analysisperiod.py
  ladybug/dt.py
  ladybug/header.py
  ladybug/location.py
  ladybug/sunpath.py
  tests/dt_test.py
Labels: critical, enhancement, new development

#160 fix(wea): add missed is_leap_year input
  ladybug/wea.py
Labels: bug

#161 feat(datetime): Add to_array and from_array methods to datetime
  ladybug/analysisperiod.py
  ladybug/datacollection.py
  ladybug/dt.py
  ladybug/stat.py
  tests/dt_test.py
Labels: enhancement

#162 fix(date): Fix bug in Date.from_doy() classmethod
  ladybug/dt.py
  tests/dt_test.py
Labels: bug, critical

#164 feat(iterable): Update for compatibility with Python 3.8
  ladybug/_datacollectionbase.py
  ladybug/datacollection.py
  ladybug/legend.py
  ladybug/wea.py
Labels: enhancement
