Repository ladybug-tools/ladybug, pull requests merged in 2019-04, with the labels that each got.

#130 feat(skymodel): Added Perez Luminous Efficacy Model
  ladybug/_datacollectionbase.py
  ladybug/skymodel.py
  ladybug/wea.py
  tests/skymodel_test.py
  tests/wea_test.py
Labels: enhancement, new development

#138 docs(conf.py): set version to ''
  docs/conf.py
Labels: bug, documentation

#139 docs(conf.py): set version in conf.py
  docs/conf.py
Labels: documentation
