Repository ladybug-tools/ladybug, pull requests merged in 2019-10, with the labels that each got.

#167 refactor(dict): Add type key to to_dict() of ladybug core objects
  ladybug/_datacollectionbase.py
  ladybug/analysisperiod.py
  ladybug/color.py
  ladybug/datacollection.py
  ladybug/datatype/base.py
  ladybug/designday.py
  ladybug/dt.py
  ladybug/epw.py
  ladybug/graphic.py
  ladybug/header.py
  ladybug/legend.py
  ladybug/location.py
  ladybug/stat.py
  ladybug/wea.py
  tests/location_test.py
Labels: core, ladybug

#173 #153: Derivative Section updated and typos
  README.md
  docs/README.md
Labels: core, hacktoberfest, ladybug

#170 Update several things in the formatting of the documentation #158
  docs/_static/custom.css
  docs/_templates/layout.html
  docs/conf.py
  ladybug/_datacollectionbase.py
  ladybug/analysisperiod.py
  ladybug/color.py
  ladybug/datacollection.py
  ladybug/datacollectionimmutable.py
  ladybug/datatype/__init__.py
  ladybug/datatype/angle.py
  ladybug/datatype/area.py
  ladybug/datatype/base.py
  ladybug/datatype/distance.py
  ladybug/datatype/energy.py
  ladybug/datatype/energyflux.py
  ladybug/datatype/energyintensity.py
  ladybug/datatype/fraction.py
  ladybug/datatype/generic.py
  ladybug/datatype/illuminance.py
  ladybug/datatype/luminance.py
  ladybug/datatype/mass.py
  ladybug/datatype/massflowrate.py
  ladybug/datatype/power.py
  ladybug/datatype/pressure.py
  ladybug/datatype/rvalue.py
  ladybug/datatype/specificenergy.py
  ladybug/datatype/speed.py
  ladybug/datatype/temperature.py
  ladybug/datatype/temperaturedelta.py
  ladybug/datatype/temperaturetime.py
  ladybug/datatype/thermalcondition.py
  ladybug/datatype/uvalue.py
  ladybug/datatype/volume.py
  ladybug/datatype/volumeflowrate.py
  ladybug/designday.py
  ladybug/dt.py
  ladybug/epw.py
  ladybug/futil.py
  ladybug/graphic.py
  ladybug/header.py
  ladybug/legend.py
  ladybug/location.py
  ladybug/rootfind.py
  ladybug/skymodel.py
  ladybug/stat.py
  ladybug/sunpath.py
  ladybug/wea.py
Labels: core, documentation, enhancement, hacktoberfest, ladybug

#180 Fix: Moving Directories Under Tests to Fixtures Folder And Correcting Paths
  tests/datacollection_test.py
  tests/designday_test.py
  tests/epw_test.py
  tests/fixtures/ddy/chicago.ddy
  tests/fixtures/ddy/chicago_edited.ddy
  tests/fixtures/ddy/chicago_monthly.ddy
  tests/fixtures/ddy/tokyo.ddy
  tests/fixtures/epw/chicago.epw
  tests/fixtures/epw/tokyo.epw
  tests/fixtures/stat/chicago.stat
  tests/fixtures/stat/santamonica.stat
  tests/fixtures/stat/tokyo.stat
  tests/fixtures/wea/san_francisco_10min.wea
  tests/futil_test.py
  tests/stat_test.py
  tests/wea_test.py
Labels: core, enhancement, good first issue, hacktoberfest, ladybug

#181 fix(requirements): Use >= instead of ==
  requirements.txt
Labels: core, critical, ladybug

#183 fix(travis): update version of node to 12
  .travis.yml
Labels: bug, core, critical, ladybug
